//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// AddEffectListRequest defines model for AddEffectListRequest.
type AddEffectListRequest struct {
	Effects        *[]EffectPair `json:"effects,omitempty"`
	Name           string        `json:"name"`
	SwitchInterval *int          `json:"switch_interval,omitempty"`
}

// BrightnessRequest defines model for BrightnessRequest.
type BrightnessRequest struct {
	Brightness *int `json:"brightness,omitempty"`
}

// BrightnessResponse defines model for BrightnessResponse.
type BrightnessResponse struct {
	Brightness int `json:"brightness"`
}

// EffectList defines model for EffectList.
type EffectList struct {
	Effects        []EffectPair `json:"effects"`
	Name           string       `json:"name"`
	SwitchInterval int          `json:"switch_interval"`
}

// EffectListNamesResponse defines model for EffectListNamesResponse.
type EffectListNamesResponse struct {
	ListNames []string `json:"list_names"`
}

// EffectPair defines model for EffectPair.
type EffectPair struct {
	Primary   string  `json:"primary"`
	Secondary *string `json:"secondary,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse map[string]string

// IndexResponse defines model for IndexResponse.
type IndexResponse struct {
	Index int `json:"index"`
}

// InfoResponse defines model for InfoResponse.
type InfoResponse struct {
	Info string `json:"info"`
}

// NameResponse defines model for NameResponse.
type NameResponse struct {
	Name string `json:"name"`
}

// PowerRequest defines model for PowerRequest.
type PowerRequest struct {
	Power *bool `json:"power,omitempty"`
}

// PowerResponse defines model for PowerResponse.
type PowerResponse struct {
	Power bool `json:"power"`
}

// SelectCurrentEffectByIndexRequest defines model for SelectCurrentEffectByIndexRequest.
type SelectCurrentEffectByIndexRequest struct {
	Index int `json:"index"`
}

// State defines model for State.
type State struct {
	Brightness int  `json:"brightness"`
	Power      bool `json:"power"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status string `json:"status"`
}

// UiConfig defines model for UiConfig.
type UiConfig struct {
	Colors   []string `json:"colors"`
	NumBands int      `json:"num_bands"`
}

// ListName defines model for ListName.
type ListName = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// SetCurrentEffectIndex200JSONResponseBody defines parameters for SetCurrentEffectIndex.
type SetCurrentEffectIndex200JSONResponseBody struct {
	union json.RawMessage
}

// SetPower200JSONResponseBody defines parameters for SetPower.
type SetPower200JSONResponseBody struct {
	union json.RawMessage
}

// CreateEffectListJSONRequestBody defines body for CreateEffectList for application/json ContentType.
type CreateEffectListJSONRequestBody = AddEffectListRequest

// SetCurrentEffectIndexJSONRequestBody defines body for SetCurrentEffectIndex for application/json ContentType.
type SetCurrentEffectIndexJSONRequestBody = SelectCurrentEffectByIndexRequest

// AppendEffectPairToListJSONRequestBody defines body for AppendEffectPairToList for application/json ContentType.
type AppendEffectPairToListJSONRequestBody = EffectPair

// RemoveEffectPairFromListJSONRequestBody defines body for RemoveEffectPairFromList for application/json ContentType.
type RemoveEffectPairFromListJSONRequestBody = EffectPair

// PreviewEffectPairJSONRequestBody defines body for PreviewEffectPair for application/json ContentType.
type PreviewEffectPairJSONRequestBody = EffectPair

// SetBrightnessJSONRequestBody defines body for SetBrightness for application/json ContentType.
type SetBrightnessJSONRequestBody = BrightnessRequest

// SetPowerJSONRequestBody defines body for SetPower for application/json ContentType.
type SetPowerJSONRequestBody = PowerRequest

// AsIndexResponse returns the union data inside the SetCurrentEffectIndex200JSONResponseBody as a IndexResponse
func (t SetCurrentEffectIndex200JSONResponseBody) AsIndexResponse() (IndexResponse, error) {
	var body IndexResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromIndexResponse overwrites any union data inside the SetCurrentEffectIndex200JSONResponseBody as the provided IndexResponse
func (t *SetCurrentEffectIndex200JSONResponseBody) FromIndexResponse(v IndexResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeIndexResponse performs a merge with any union data inside the SetCurrentEffectIndex200JSONResponseBody, using the provided IndexResponse
func (t *SetCurrentEffectIndex200JSONResponseBody) MergeIndexResponse(v IndexResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInfoResponse returns the union data inside the SetCurrentEffectIndex200JSONResponseBody as a InfoResponse
func (t SetCurrentEffectIndex200JSONResponseBody) AsInfoResponse() (InfoResponse, error) {
	var body InfoResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInfoResponse overwrites any union data inside the SetCurrentEffectIndex200JSONResponseBody as the provided InfoResponse
func (t *SetCurrentEffectIndex200JSONResponseBody) FromInfoResponse(v InfoResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInfoResponse performs a merge with any union data inside the SetCurrentEffectIndex200JSONResponseBody, using the provided InfoResponse
func (t *SetCurrentEffectIndex200JSONResponseBody) MergeInfoResponse(v InfoResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SetCurrentEffectIndex200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SetCurrentEffectIndex200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsPowerResponse returns the union data inside the SetPower200JSONResponseBody as a PowerResponse
func (t SetPower200JSONResponseBody) AsPowerResponse() (PowerResponse, error) {
	var body PowerResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPowerResponse overwrites any union data inside the SetPower200JSONResponseBody as the provided PowerResponse
func (t *SetPower200JSONResponseBody) FromPowerResponse(v PowerResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePowerResponse performs a merge with any union data inside the SetPower200JSONResponseBody, using the provided PowerResponse
func (t *SetPower200JSONResponseBody) MergePowerResponse(v PowerResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInfoResponse returns the union data inside the SetPower200JSONResponseBody as a InfoResponse
func (t SetPower200JSONResponseBody) AsInfoResponse() (InfoResponse, error) {
	var body InfoResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInfoResponse overwrites any union data inside the SetPower200JSONResponseBody as the provided InfoResponse
func (t *SetPower200JSONResponseBody) FromInfoResponse(v InfoResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInfoResponse performs a merge with any union data inside the SetPower200JSONResponseBody, using the provided InfoResponse
func (t *SetPower200JSONResponseBody) MergeInfoResponse(v InfoResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SetPower200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SetPower200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get UI visualization config
	// (GET /config)
	GetConfig(w http.ResponseWriter, r *http.Request)
	// List all effect lists
	// (GET /effect-list)
	GetEffectLists(w http.ResponseWriter, r *http.Request)
	// Create an effect list
	// (POST /effect-list)
	CreateEffectList(w http.ResponseWriter, r *http.Request)
	// Get the current effect list
	// (GET /effect-list-current)
	GetCurrentEffectList(w http.ResponseWriter, r *http.Request)
	// Get current effect pair index
	// (GET /effect-list-current/index)
	GetCurrentEffectIndex(w http.ResponseWriter, r *http.Request)
	// Select current effect pair by index
	// (POST /effect-list-current/index)
	SetCurrentEffectIndex(w http.ResponseWriter, r *http.Request)
	// Get the current effect list name
	// (GET /effect-list-current/name)
	GetCurrentEffectListName(w http.ResponseWriter, r *http.Request)
	// Select the next effect pair
	// (POST /effect-list-current/next)
	SelectNextEffect(w http.ResponseWriter, r *http.Request)
	// Get the current effect pair
	// (GET /effect-list-current/pair)
	GetCurrentEffectPair(w http.ResponseWriter, r *http.Request)
	// Select the previous effect pair
	// (POST /effect-list-current/previous)
	SelectPreviousEffect(w http.ResponseWriter, r *http.Request)
	// List effect list names
	// (GET /effect-list-names)
	GetEffectListNames(w http.ResponseWriter, r *http.Request)
	// Remove an effect list
	// (DELETE /effect-list/{list_name})
	DeleteEffectList(w http.ResponseWriter, r *http.Request, listName ListName)
	// Get an effect list by name
	// (GET /effect-list/{list_name})
	GetEffectListByName(w http.ResponseWriter, r *http.Request, listName ListName)
	// Select the current effect list
	// (POST /effect-list/{list_name})
	SelectEffectList(w http.ResponseWriter, r *http.Request, listName ListName)
	// Append an effect pair to a custom list
	// (POST /effect-list/{list_name}/append)
	AppendEffectPairToList(w http.ResponseWriter, r *http.Request, listName ListName)
	// Remove an effect pair from a custom list
	// (DELETE /effect-list/{list_name}/remove)
	RemoveEffectPairFromList(w http.ResponseWriter, r *http.Request, listName ListName)
	// Preview a primary/secondary effect pair
	// (POST /effect-pair/preview)
	PreviewEffectPair(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Get runtime state
	// (GET /state)
	GetState(w http.ResponseWriter, r *http.Request)
	// Set brightness
	// (POST /state/brightness)
	SetBrightness(w http.ResponseWriter, r *http.Request)
	// Set power state
	// (POST /state/power)
	SetPower(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetConfig operation middleware
func (siw *ServerInterfaceWrapper) GetConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEffectLists operation middleware
func (siw *ServerInterfaceWrapper) GetEffectLists(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEffectLists(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEffectList operation middleware
func (siw *ServerInterfaceWrapper) CreateEffectList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEffectList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentEffectList operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentEffectList(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentEffectList(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentEffectIndex operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentEffectIndex(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentEffectIndex(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetCurrentEffectIndex operation middleware
func (siw *ServerInterfaceWrapper) SetCurrentEffectIndex(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetCurrentEffectIndex(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentEffectListName operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentEffectListName(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentEffectListName(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SelectNextEffect operation middleware
func (siw *ServerInterfaceWrapper) SelectNextEffect(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SelectNextEffect(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentEffectPair operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentEffectPair(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentEffectPair(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SelectPreviousEffect operation middleware
func (siw *ServerInterfaceWrapper) SelectPreviousEffect(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SelectPreviousEffect(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEffectListNames operation middleware
func (siw *ServerInterfaceWrapper) GetEffectListNames(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEffectListNames(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteEffectList operation middleware
func (siw *ServerInterfaceWrapper) DeleteEffectList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "list_name" -------------
	var listName ListName

	err = runtime.BindStyledParameterWithOptions("simple", "list_name", r.PathValue("list_name"), &listName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteEffectList(w, r, listName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEffectListByName operation middleware
func (siw *ServerInterfaceWrapper) GetEffectListByName(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "list_name" -------------
	var listName ListName

	err = runtime.BindStyledParameterWithOptions("simple", "list_name", r.PathValue("list_name"), &listName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEffectListByName(w, r, listName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SelectEffectList operation middleware
func (siw *ServerInterfaceWrapper) SelectEffectList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "list_name" -------------
	var listName ListName

	err = runtime.BindStyledParameterWithOptions("simple", "list_name", r.PathValue("list_name"), &listName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SelectEffectList(w, r, listName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AppendEffectPairToList operation middleware
func (siw *ServerInterfaceWrapper) AppendEffectPairToList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "list_name" -------------
	var listName ListName

	err = runtime.BindStyledParameterWithOptions("simple", "list_name", r.PathValue("list_name"), &listName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AppendEffectPairToList(w, r, listName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveEffectPairFromList operation middleware
func (siw *ServerInterfaceWrapper) RemoveEffectPairFromList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "list_name" -------------
	var listName ListName

	err = runtime.BindStyledParameterWithOptions("simple", "list_name", r.PathValue("list_name"), &listName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "list_name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveEffectPairFromList(w, r, listName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PreviewEffectPair operation middleware
func (siw *ServerInterfaceWrapper) PreviewEffectPair(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PreviewEffectPair(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetState operation middleware
func (siw *ServerInterfaceWrapper) GetState(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetState(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetBrightness operation middleware
func (siw *ServerInterfaceWrapper) SetBrightness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetBrightness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetPower operation middleware
func (siw *ServerInterfaceWrapper) SetPower(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetPower(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/config", wrapper.GetConfig)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/effect-list", wrapper.GetEffectLists)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/effect-list", wrapper.CreateEffectList)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/effect-list-current", wrapper.GetCurrentEffectList)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/effect-list-current/index", wrapper.GetCurrentEffectIndex)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/effect-list-current/index", wrapper.SetCurrentEffectIndex)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/effect-list-current/name", wrapper.GetCurrentEffectListName)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/effect-list-current/next", wrapper.SelectNextEffect)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/effect-list-current/pair", wrapper.GetCurrentEffectPair)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/effect-list-current/previous", wrapper.SelectPreviousEffect)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/effect-list-names", wrapper.GetEffectListNames)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/effect-list/{list_name}", wrapper.DeleteEffectList)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/effect-list/{list_name}", wrapper.GetEffectListByName)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/effect-list/{list_name}", wrapper.SelectEffectList)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/effect-list/{list_name}/append", wrapper.AppendEffectPairToList)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/effect-list/{list_name}/remove", wrapper.RemoveEffectPairFromList)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/effect-pair/preview", wrapper.PreviewEffectPair)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/state", wrapper.GetState)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/state/brightness", wrapper.SetBrightness)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/state/power", wrapper.SetPower)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FtZc9s4Ev4rKGQeqcNXDlXlwU7srGu9iSp2ah9srQ2RLRETEuAAoGSNS/99CwcpnpJ8yJma3ZeURRzd",
	"+PoGOg/Y53HCGTAl8eABJ0SQGBQI8+uCSvWVxKD/hnsSJxHgAZaKKOpjD1OGBzghKsQeZmYajqhUt+Zv",
	"Dwv4I6UCAjxQIgUPSz+EmOi9YsougE1ViAd7HlaLxG4rKJvi5XKpl8qEMwmGixMSfIc/UpBK//I5U8DM",
	"nyRJIuoTRTnr/S45099WRH4TMMED/Ka3OmHPjsreqRBcfHdELMkApC9oojfDA3zOZiSiARKWcBcvPfyJ",
	"s0lE/Vfk4jtIngofEIkEkGCB4J5KJREXKEgtVUBUQWz4O+NiTIMA2Osx+C0BYTZGVKJJRt9w85WrM56y",
	"4BegNScSMa7QRNPvYj3TbaJpHAfB6WQCvtLaXVCsRPAEhKJW6cBMMX8GMCFppPDgeuRhjbbcyKpZPCRU",
	"aCRYGkVkrE3H2oHTdyIEWZjxmoVNyIwLqkBib72teFjOqfLDW8oUiBmJSvwe9M1yGqcxHvRbGdFrpyCw",
	"NbzMZq8tX6N8Gh//Dr7CHr7v+KkQwFQnWaiQsw7jSk+4CgENzRc0XASEKeqjmAcQITc/WqAA/IgIkOjO",
	"AXyHiEQEZawhSdk0ArRC0EPjVCFgQcIpU8jnASAlgCiJqLKLtdPpIk3+C0fHw3MkQ55GAUolIBUCMkgj",
	"GZIEUMD9NAamIEAhCOjeMI3iiaDTUDGQsqAQuTwe8Dgfx4O99/2lV9GW4vgDjsm9xXz/6OjREiijXeHN",
	"Kf9umNugDoVtRg1srmxqrTE9wX4220uwYCQ2Ienx1pLvUrWWbayjvqOXH3Y9SDqslgRaRiyPo7LE4/Uq",
	"+GZnLvqk2nnL0FVOUKDRzqsRQo29RNCYiEVZCpcJ+Eqk8ZWgRBvxNt4LfM6C+k6M/NTgtphLnimUz5Mx",
	"1XiYUvCoK6geLvNgj298yyqY4E082I2aOPgHkEiFRRZIEFAdukg0LDFTQ6lg6/v9vg67/8RNnuKcBXDf",
	"fkiqh0uHfJzG2/WjRsITvo7uhJexHfI5CKRVGVDK/JCwKWzG1uzTRF7bUjt51p7ArqfXHP+WnmW/OVAk",
	"esiqa80Pu7GHNrUecx4BYc1RwNFsDABbEW0gUjIeM6/ptJcQga8+2RBureJk4VStJXnanaZdap2pEyyH",
	"uJyqDXFbBzxvhVa+RauE6uB5m0KkZj5d4/SlGa+YioAZhTlKk4CoLYzE7dFE/gfVFQyd1gn7POKiGmne",
	"9PsHkyNtJm/2J4fjd+avt2+P9j7slYJOQpQCoRPw/7y57nc+HHfOSGcyeni7/A17m0KS9vHx7ZiwoEz+",
	"fUFSe5tjcb6Hl52lDoBelLmicuGgU0Zdogjiaz8vTNL4haOYTl11wyfm21AuLk4/I5IGlHcEEF/RGaCL",
	"0883zKznUQSie8Nu2FVI5WpPKtGYSAgQZ2Yflw9n2fIZkUrzQPXZdXLqSip2w+5IQntZ8iu7yeIOERYg",
	"83ksOAl8InW1rkcM4X/D+JL7P0EhwVMFEhFRSnrnVIXo7r4zh7E08zr57ndoDD5JJdywbwkwzdFBt48C",
	"Dlk5JWISRQuX1K8oxSAlmQKSOi+Ppc6pPayosgpsMTsenmMPz0BIi3m/u9fta/nzBBhJKB7gg26/e4A9",
	"c6NgtKHn5/o6BeNmeFZvngd4gL+AchpduTEwUfKFys7cahoqzhMtC5+nTBmpBFQmEVkgq4K5Jo0Fn0sQ",
	"yA+JUK4cTWObP+kzoB/naEZlSiL6p5W8n51KkanUCu5YGOm1PZtgdiKXardBs8o15XPxeUTSbgqAeuZZ",
	"g+44ilCitUFqrdTojVMaqQ5lCFaZl6zCpbdHJIpKkwpAuazNnnpkPLpsgOeTLiChwLH1JyDVCQ8WL6Y7",
	"jVcNy7L3clH7ryafHzbe2PzX147NN6pJJkqrssaPcnvTc2i5baKdn6pXuMQzSz5sXpLft5VVwMoOkZKi",
	"tKtAxWKyu4u1TqWY6+TqsSP/UhRLXQyOleJRHeaHmwHMr+DqLqcYhZphzCgX4GxHs5dnfFtharLHXYJa",
	"roTW4Gr4RtSGZWkyXQgqaNfAqwCXECrsRhvha/NHl60AvbxT2pzP78BDcQbfJnhw/SixeZtmF6rO5ahB",
	"ypeZQI10PMS1nEwaY+tulJ3JxGrtUeJELYpW9gTP9nTDtOw2qtd4saWGtRloVgVv7fO+Zo84OzLRUtG+",
	"nedD+hC7dH/IXeo9EWK4t7Vwi4lr4X6Fe4fxL3V/X2He7sW6L6THGmSNSZHCk8FN3D3kVvo7tJR2HLPt",
	"/fRGzdWc70ppnwepgBnlqdyks0M3739JbzNsngV0fn+/uUQzzwGvk2aWXx6aQNYTEJ/U6qzGYqzqPuXW",
	"qXjvIX+BWNpLmQjs5V6lys4KQ8MEurPXt+4ixD2D3CGfMMYVGgOy+wRd7FUQ/2wGXi6tf/Wyy5zsWWXX",
	"weYlqzaCZ5rTd4j5bPtCzdvCTE4Wu05L1pdj/yLKDymbvng9VgZJp3uVVKR+sVHo1GlJq1dTenlGtxx5",
	"a539X6HovWyuw35VPr65Vt7ez/VIkoBtismk8DxnF/OATmiTtzs2lFapyhV3Un2G5uyiHq0mUy9beD5d",
	"CzNX/CJKuGO/+7wbNaspBR9kcirFEUF+KhWPn6HvwgSBlwzv7RpvA85Kn84Ej/+v839XnV+faxgVngge",
	"P0GJ9VpbHcG8vThyL7OVivPvpCuV9+oGfclep+dEZi/UxXTodfo+r+ovqqZL0CcMCVCpYEiFVFpt0MHc",
	"qUhMGJmCazA03/Mmw7xfkU4ZFyCRColC9m097zSsPNe6pkNH8bB/aC4VU/aT8XmulqZCqtZRGYoEuRam",
	"Xt4X1VJ/Ot11C532hqbDaF29aXuQnpbYuad5s4L/1P/OSJRWmpJWrbabpFpph2rMAsWM+oCoRPZkiypu",
	"dg/kh+D/LIDjTmlBkVnDSBsmtqNkx1a09obTdI/YJ9C8f6Tp2UGkTNEYbN9U4byWQOG4vXI7TOuTw6qz",
	"dEeuq95W+8oerKF3tukZP5/V4MgeGfgqBYQqyHStyPLOo1ZpDV2T0S4EVepo+2XPP+Uet+c//9g2w4JI",
	"7QuQMp+y/1Lh3v4cqhBY83oh4SerRscm6ZsOWDHLstIy9xfcJxEKYAYRT3SYQXYu9nAqIjzAoVLJoNeL",
	"9LyQSzX48P7dW5OyOkJZ72PmETWi7kvW07L64tzU6kMpPyoubbj7rC/LQpNmp7HbyJ6YCnvBhQcOiY7i",
	"HT+iWqs87BqLCqp25e7PqtpWDDvF1njbWHbd9/b2vcNDb2//vbd/dOR96HsHfe9wVO+VzzrR8ru9x7QP",
	"rm23tls39KXZjic8wL257GVtbCs9Mk1GkVYD12Bl0N4euTFlRCzOzKun+b1Q0Df/cUsL5JYGKKVMvcee",
	"Gdkz+5md8yEPHX/se+jk456HPn3cdzP3bxW/NXcZ+PuXE5TQe4iQHpAeUqEAsD9QAgJdnH7W+LQLkfsK",
	"VMedTwOyiDgJLumfrjPScnSMB+/2973s5wkeHB3085+f8GDv8HC/lIJM3LEdCo3tkwX0I6iAf3H6Gbnt",
	"0UTXh7kMRsv/BgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
